version: '3.9'

services:
  php:
    tty: true
    build:
      context: ./
      dockerfile: build/php/Dockerfile
      args:
        APP_DIR: ${APP_CODE_PATH_CONTAINER}
    working_dir: ${APP_CODE_PATH_CONTAINER}
    networks:
      - php_network
    environment:
      - DEBIAN_FRONTEND=noninteractive
networks:
  php_network:
    driver: bridge
